Vagrant.configure("2") do |masters|

    masters.vm.provider "virtualbox" do |vmaster|
        vmaster.memory = 4096
        vmaster.cpus = 4
    end

    masters.vm.define "master" do |master|
        master.vm.box = "ubuntu/xenial64"
        master.vm.network "public_network"
    end

end